version: "3.4"
services:
  postgres:
    image: postgres
    container_name: nishdb
    environment:
      - POSTGRES_DB=nishdb
      - POSTGRES_USER=alperen
      - POSTGRES_PASSWORD=yZ5ePXX2VN27jdx
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  backend:
    image: alperengumrukcu/nish-project-docker
    container_name: nish-project-backend
    build: ./
    ports:
      - "8080:8080"

    depends_on:
      - postgres

    environment:
      - spring.datasource.url=jdbc:postgresql://nishdb:5432/nishdb
      - spring.datasource.username=alperen
      - spring.datasource.password=yZ5ePXX2VN27jdx
      - spring.jpa.hibernate.ddl-auto=update